### ISSUE TITLE
getCards with fields set doesn't work

### ISSUE THREAD

**Issue by m-krajcovic** [nasajoey/Java-API-to-mtgdb#12]
Hi, I just noticed that getCards(Set<String> fields) doesn't really work for me. I tried to get only card's names but instead got cards with default values(-1 and Value not set.) in every field. I will try to get it working myself but I would be glad if you knew where is the problem

**Comment by alotau** [comment]
Checking on it tonight.  If you have some time and feel like creating some new unit tests, I'd happily include them.  That would help me make sure the code is doing what it is supposed to.  As you are finding out, I haven't thoroughly tested all the features yet.  Will keep you posted on this bug.

**Comment by alotau** [comment]
Sorry to punt on this issue, but the problem seems to lie with the web service rather than this library.  The field names are in a different case when returned via this type of query and that ruins how the fields are populated in the Java code.  For example with this type of query, we get an "Id" field instead of an "id" field.

Clearly we could make a change to the Java client to address this, but I think the proper fix should be in the web service to be consistent.  I submitted this issue:

https://github.com/planeswalkers/api.mtgdb.info/issues/85

If you'd like to follow it there.

I'll keep this issue open until there is a resolution.

**Comment by alotau** [comment]
OK, I just added a workaround to the java code that should be more robust to these variations in field names.  Let me know how it works for you.  Thanks for the report!
